limits:
  aqua_affinity: 1
  bane_of_arthropods: 32767
  blast_protection: 32767
  channeling: 1
  binding_curse: 1
  vanishing_curse: 1
  depth_strider: 3
  efficiency: 32767
  feather_falling: 32767
  fire_aspect: 5
  fire_protection: 32767
  flame: 1
  fortune: 10
  frost_walker: 2
  impaling: 32767
  infinity: 1
  knockback: 2
  looting: 10
  loyalty: 3
  luck_of_the_sea: 10
  lure: 10
  mending: 1
  multishot: 1
  piercing: 32767
  power: 32767
  projectile_protection: 32767
  protection: 32767
  punch: 2
  quick_charge: 3
  respiration: 32767
  riptide: 3
  sharpness: 32767
  silk_touch: 1
  smite: 32767
  soul_speed: 3
  sweeping: 32767
  swift_sneak: 5
  thorns: 32767
  unbreaking: 32767
